export const legacyCatalog = {
  productSeries: [
    "PVC 70AD",
    "PVC 76MD",
    "PVC 82MD",
    "PVC/ALU 70AD AK",
    "PVC/ALU 76MD AK",
    "PVC/ALU 82MD AK",
    "ALU 65TT",
    "ALU 85TT",
    "ALU 90TT",
    "ALU 150K",
    "ALU Fasada",
    "DRVO/ALU UniOne St.",
    "DRVO/ALU Complanare",
    "DRVO/ALU Maagis 40"
  ],
  materialStatuses: ["PRIPREMA", "DOSTUPNO", "NARUCENO"],
  glassStatuses: [
    "DSL - PRIPREMA",
    "TRL - PRIPREMA",
    "DSL - DOSTUPNO",
    "TRL - DOSTUPNO",
    "DSL - NARUCENO",
    "TRL - NARUCENO"
  ],
  panelStatuses: [
    "GLATKI - PRIPREMA",
    "DEKORATIVNI - PRIPREMA",
    "GLATKI - DOSTUPNO",
    "DEKORATIVNI - DOSTUPNO",
    "GLATKI - NARUCENO",
    "DEKORATIVNI - NARUCENO"
  ],
  colors: [
    "ANTRAZIT",
    "ANTRAZIT U. MAT",
    "BIANCO",
    "BIANCO VENATO",
    "GOLDEN OAK",
    "NUSSBAUM",
    "MARONE",
    "PEPER OAK",
    "RAL8017",
    "RAL9006",
    "RAL9010",
    "RAL9016",
    "RUSTIC OAK",
    "SCHWARZBRAUN",
    "GREZZO",
    "S2500 INTERPON GRIS",
    "IC O50 ICONA SALE"
  ],
  hardwareModels: ["HOPE", "COLOMBO"],
  hardwareColors: ["BIJELA", "SIVA", "ANTRAZIT", "ZLATNA", "BRONZA", "BRAUN", "CRNA"],
  capColors: ["BIJELA", "SIVA", "ANTRAZIT", "BRAUN", "CRNA"],
  plugColors: ["BIJELA", "ANTRAZIT", "KARAMEL", "CRNA", "SPECIAL", "BIJELO/CRNO RAL"],
  trims: ["30", "50"],
  stockCategories: [
    "PVC PROFILI",
    "ALU PROFILI",
    "DRVO PROFILI",
    "OJACANJA",
    "KVAKE",
    "KAPICE",
    "CEPOVI",
    "JEDNOSLOJNO STAKLO",
    "DVOSLOJNO STAKLO",
    "TROSLOJNO STAKLO",
    "GLATKI PANEL",
    "DEKORATIVNI PANEL",
    "SPOJNICE",
    "DIHTUNZI",
    "SARAFI",
    "FOLIJE",
    "VISAK MATERIJALA"
  ],
  units: ["kg", "m", "m2", "m3", "komad", "set"],
  clients: ["MALEGORI", "PROMONT WINDOWS", "S.B.I", "SEM D.O.O", "TOP WIN"],
  workers: ["SEJO", "ADVAN"],
  documentGroups: [
    "SKICE",
    "REZNA LISTA",
    "SPEC. MATERIJALA",
    "PONUDA/UGOVOR",
    "ORIGINALNE MJERE",
    "PROFILI",
    "OJACANJA",
    "OKOVI",
    "STAKLO",
    "PANELI",
    "TRANSPORT",
    "IZVOZ",
    "PROFORMA",
    "TRANSPORT SLIKA 1",
    "TRANSPORT SLIKA 2"
  ],
  suppliers: [
    "FIKO COMERC",
    "PC MARKET",
    "EURO INOX",
    "KOVING",
    "NAMJESTAJ I ST. BEGANOVIC",
    "ELEKTROINSTALACIJE",
    "VEKA",
    "FORMETAL",
    "HP FLUID",
    "ABBA",
    "INTERBUTAN",
    "PILANA TUZLAK",
    "MTK OMORIKA",
    "JP-TIHOMIR STEVKOVIC",
    "ELEKTRO DZANIC",
    "HADZALIC",
    "ELUMATEC",
    "CENTRODOM",
    "SCHACHERMAYER",
    "TERGUS",
    "DEKARTA",
    "DASPROM",
    "ZEP-ING",
    "VBH",
    "WURTH",
    "ZEKA",
    "EURO JET",
    "CISTOCA",
    "EMKA D.O.O",
    "KAMASS",
    "EUROROAL",
    "HALKO D.O.O",
    "MIND",
    "ASES TEAM D.O.O",
    "FAGUS",
    "ZANATSTVO",
    "KOVEX",
    "AUTO-STIL",
    "ANNOA",
    "COLORLAND",
    "FISCATEC",
    "METALOPROIZVOD TURIJA",
    "HMD-PRO",
    "BHL",
    "ERONET",
    "FAVORIT",
    "TRANSKOP",
    "TERMOGLAS",
    "ALATUSA",
    "EUROMETALI",
    "GRAFIS",
    "LAGERMAX",
    "HH-INOX",
    "GRAFO OSTROZAC",
    "PROFINE",
    "METALKA"
  ]
} as const;

export type LegacyCatalog = typeof legacyCatalog;
